### PR TITLE
fix(cc-toggle / cc-select): add and reflect name attributes

### LINKED ISSUE #581: cc-toggle / cc-select: add a `name` prop to populate the name attribute of these form controls
The `cc-toggle` component implements a hard coded name attribute.
We need the `name` attribute to be populated from a prop so that it can be retrieved in a `FormData` when we move to this.
This is a breaking change.

The `cc-select` element implements a `name` prop that is not used within the component :facepalm:.
This prop should populate a `name` attribute on the `select` element.

### PR DESCRIPTION
**Pull request by HeleneAmouzou**
Fixes #581

### CODE REVIEW

File: src/components/cc-toggle/cc-toggle.js [hunk 1]
```diff
@@ -130,7 +134,7 @@ export class CcToggle extends LitElement {
           ${repeat(this.choices, ({ value }) => value, ({ label, image, value }) => html`
             <input
               type=${type}
-              name="toggle"
+              name=${this.name ?? 'toggle'}
```
Comment (pdesoyres-cc) [inline src/components/cc-toggle/cc-toggle.js:137]: I think you put a fallback to 'toggle' to avoid a breaking change.
I would prefer to introduce a breaking change and have a homogeneous way of handling name attributes on all our input components.

If you don't know what to do with this comment, let's wait for other reviewers to give their thoughts about that.

**Review by pdesoyres-cc — COMMENTED** [review]
Nice first PR Hélène :clap:

I have just one comment about breaking change or not.

File: src/components/cc-toggle/cc-toggle.js [hunk 2]
```diff
@@ -51,6 +51,7 @@ export class CcToggle extends LitElement {
       inline: { type: Boolean, reflect: true },
       legend: { type: String },
       multipleValues: { type: Array, attribute: 'multiple-values', reflect: true },
+      name: { type: String, reflect: true },
```
Comment (hsablonniere) [inline src/components/cc-toggle/cc-toggle.js:54]: issue(mild): The reflect is needed when we use the property in CSS selector. In this situation, we can remove it.

**Review by hsablonniere — CHANGES_REQUESTED** [review]
Well done @HeleneAmouzou :+1: 

suggestion: I don't think we need the comment about name defaulting to toggle at two places. One is enough, but maybe it's just me.

File: src/components/cc-toggle/cc-toggle.js (hunk 2 above)
Comment (florian-sanders-cc) [reply src/components/cc-toggle/cc-toggle.js:54]: I would prefer we keep reflecting it.

The name attribute is useful in a native context where element internals is not supported to retrieve elements participating in a form:

```js
const myFormElements = form.querySelectorAll([name])
```

We also use the name attribute in our experimentations with @pdesoyres-cc :wink:

**Review by pdesoyres-cc — APPROVED** [review]
LGTM. This is perfect

**Comment by HeleneAmouzou** [comment]
> suggestion: I don't think we need the comment about name defaulting to toggle at two places. One is enough, but maybe it's just me.

I will just keep the two comments, it seems clearer to me.

**Review by hsablonniere — APPROVED** [review]
All good!

**Review by florian-sanders-cc — APPROVED** [review]
LGTM! Gg @HeleneAmouzou !!
