### PR TITLE
fix(cc-img): populate alt value

### LINKED ISSUE #726: cc-img: use `text` value as `alt` value for the inner `<img>` tag
# Context

The `cc-img` component has a `text` prop that is used to display a text when the image is not loaded.
The `alt` attribute of the `` tag inside the component is always empty and there is no way to set it from outside the component.

# Solutions

Either use `text` value as `alt` value (when there is no error), or introduce a separate `accessible-name` prop.

### PR DESCRIPTION
**Pull request by HeleneAmouzou**
Fixes #726

### CODE REVIEW

File: src/components/cc-img/cc-img.js [hunk 1]
```diff
@@ -20,7 +20,7 @@ export class CcImg extends LitElement {
     return {
       skeleton: { type: Boolean, reflect: true },
       src: { type: String },
-      text: { type: String },
+      accessibleName: { type: String },
```
Comment (Galimede) [inline src/components/cc-img/cc-img.js:23]: suggestion: maybe we could add an attribute name `attribute: 'accessible-name` as it's two words?
```suggestion
      accessibleName: { type: String, attribute: 'accessible-name' },
```

**Review by Galimede — APPROVED** [review]
Just a suggestion otherwise LGTM! :+1:  :muscle:

File: src/components/cc-img/cc-img.stories.js [hunk 2]
```diff
@@ -22,24 +22,24 @@ const conf = {
 
 export const defaultStory = makeStory(conf, {
   items: [
-    { text: 'OMG' },
-    { text: 'OMG', skeleton: true },
-    { text: 'OMG', skeleton: true, src: 'http://placekitten.com/200/200' },
+    { accessibleName: 'OMG' },
+    { skeleton: true },
```
Comment (florian-sanders-cc) [inline src/components/cc-img/cc-img.stories.js:26]: **suggestion:** I remember we removed `text` / `accessibleName` here to see if the component behaved well when the prop is `undefined` / `null`.

Do we want to create a specific story for that maybe?

A copy of the `defaultStory` with no `accessibleName` in the items?

File: src/components/cc-header-orga/cc-header-orga.js [hunk 3]
```diff
@@ -66,7 +66,7 @@ export class CcHeaderOrga extends LitElement {
         ` : ''}
 
         ${!this.error ? html`
-          <cc-img class="logo" ?skeleton=${skeleton} src=${ifDefined(orga.avatar)} text=${initials}></cc-img>
+          <cc-img class="logo" ?skeleton=${skeleton} src=${ifDefined(orga.avatar)} accessibleName=${initials}></cc-img>
```
Comment (florian-sanders-cc) [inline src/components/cc-header-orga/cc-header-orga.js:69]: **nitpick:** when we're dealing with `string` and other simple types, we tend to use attributes instead of properties (same for all other occurrrences)
```suggestion
          <cc-img class="logo" ?skeleton=${skeleton} src=${ifDefined(orga.avatar)} accessible-name=${initials}></cc-img>
```

**Review by florian-sanders-cc — CHANGES_REQUESTED** [review]
Good job @HeleneAmouzou, I only have a few nitpick comments.

**Review by pdesoyres-cc — APPROVED** [review]
LGTM. Well done @HeleneAmouzou

**Review by florian-sanders-cc — APPROVED** [review]

File: src/components/cc-img/cc-img.js [hunk 4]
```diff
@@ -35,8 +35,8 @@ export class CcImg extends LitElement {
     /** @type {string|null} Sets `src` attribute on inner native `<img>` element. */
     this.src = null;
 
-    /** @type {string|null} Sets short fallback text to display when the image cannot be loaded or if `src` is not defined and `skeleton` is `false`. */
-    this.text = null;
+    /** @type {string|null} Sets short fallback accessibleName to display when the image cannot be loaded or if `src` is not defined and `skeleton` is `false`. */
```
Comment (roberttran-cc) [inline src/components/cc-img/cc-img.js:38]: **🤓 nitpick:** Actually, I think it makes more sense to keep the word "text" for this comment.

File: src/components/cc-img/cc-img.js [hunk 5]
```diff
@@ -65,14 +65,16 @@ export class CcImg extends LitElement {
...
     const isLoading = (this.src != null && !this._loaded && !this._error);
     const isSkeleton = (this.skeleton || isLoading);
-    const displayText = (this.src == null || this._error);
+    const displayAccessibleName = (this.src == null || this._error);
     return html`
-      <div class="wrapper ${classMap({ skeleton: isSkeleton, loaded: this._loaded, text: displayText })}">
-        <img src=${ifDefined(this.src ?? undefined)} @load=${this._onLoad} @error=${this._onError} alt="">
-        ${displayText ? html`
-          <div class="error-msg">${this.text}</div>
+      <div class="wrapper ${classMap({ skeleton: isSkeleton, loaded: this._loaded, accessibleName: displayAccessibleName })}">
```
Comment (roberttran-cc) [inline src/components/cc-img/cc-img.js:73]: **🎯 suggestion:** Most of the time, CSS class names are snake-cased so I would suggest this instead:
```suggestion
      <div class="wrapper ${classMap({ skeleton: isSkeleton, loaded: this._loaded, 'accessible-name': displayAccessibleName })}">
```

**Review by roberttran-cc — COMMENTED** [review]
Great job! Clean & it improves the component. :ok_hand: 

I just have a small feedback and a suggestion. :eyes:

**Review by roberttran-cc — APPROVED** [review]
Perfect! :partying_face:
