### PR TITLE
cc-button/color-fix

### LINKED ISSUE #384: cc-button: fix colors (contrast, a11y...)
## Context

The contrast for some colors are too low (according to accessibility guidelines).

This mostly concerns background color of our `<cc-button>` but because those are copy/pasted in other components as a reference, the problem is bigger than just `<cc-button>` background colors.

## TODO

* [x] audit all colors on all components
* [x] list colors that require an update (background, border, focus-ring...)
* [x] list all colors that should move to the common `defaultThemeStyles` (this can be done in multiple steps)
  * [x] move them and reuse them

## Note
* We chose not to implement default text / background colors inside our components just yet.
* This feature will be implemented at the same time as we allow for theme customization because it represents a breaking change.
* We chose not to change the colors of `cc-tile-instances` so that it remains consistent with icons (could not change icon colors because they need to remain contrasted with dark background). This component will be reworked so the color subject will be handled during this rework.

### PR DESCRIPTION
**Pull request by florian-sanders-cc**
Fixes #384 

* changes blue, green, orange and red colors (more contrasted than before with white),
* sets CSS variables for colors,
* sets CSS variables for main text and background color design tokens

### CODE REVIEW

File: src/atoms/cc-toggle.js [hunk 1]
```diff
@@ -286,7 +288,7 @@ export class CcToggle extends LitElement {
         /* NOT SELECTED */
         label {
           --color-bg: #fff;
-          --color-txt: #666;
+          --color-txt: var(--color-text-normal);
```
Comment (florian-sanders-cc) [inline src/atoms/cc-toggle.js:291]: could be set to `--color-text-light` (#404040) if you want to be closer to what we had before.

File: src/maps/cc-map.js [hunk 2]
```diff
@@ -378,10 +380,9 @@ export class CcMap extends withResizeObserver(LitElement) {
         }
 
         :host(:not(:empty)) .legend {
-          background-color: #f1f5ff;
+          background-color: var(--color-bg-neutral);
           box-shadow: inset 0 6px 6px -6px #a4b1c9;
           box-sizing: border-box;
-          color: #2e2e2e;
```
Comment (florian-sanders-cc) [inline src/maps/cc-map.js:384]: I could replace `#2e2e2e` color with `var(--color-text-default)` but I did not really see the point since it will be the default color for all texts soon.

File: src/overview/cc-header-app.js [hunk 3]
```diff
@@ -372,21 +374,10 @@ export class CcHeaderApp extends LitElement {
...
-          color: #5D5D5D;
-        }
-
-        .commit[data-type="running"] {
-          color: #2faa60;
-        }
-
-        .commit[data-type="starting"] {
-          color: #2b96fd;
-        }
```
Comment (florian-sanders-cc) [inline src/overview/cc-header-app.js:388]: we removed these because icon colors are still legacy and text is not.
We thought using color for text was not very useful here anyway since icons already convey the status.
Difference before / after in screenshots below:
image
image

File: src/overview/cc-tile-instances.js [hunk 4]
```diff
@@ -148,11 +150,11 @@ export class CcTileInstances extends LitElement {
         }
 
         .instances[data-type=running] {
-          --status-color: #2faa60;
+          --status-color: var(--color-legacy-green);
```
Comment (florian-sanders-cc) [inline src/overview/cc-tile-instances.js:153]: This is temporary because text comes with an icon which color is still legacy.
See #407

**Comment by florian-sanders-cc** [comment]
@hsablonniere should I import and use `var(--color-bg-primary)` inside the `cc-toggle` story (see below) ?

```css
As explained in the "when to use section above", this component fits well in toolbars for single or multiple choice toggles.

Here you can see a series of toolbar examples using CSS custom propreties of the component:

* \`--cc-toggle-color\` to change the main color
* \`--cc-toggle-img-filter\` so we can tweak the color of the image from default \`#6999d3\` to gray or white.
* \`--cc-toggle-img-filter-selected\` so we can tweak the color of the image from default \`#6999d3\` to gray or white. 
  `,
  css: conf.css + `
    :host {
      grid-template-columns: repeat(2, min-content);
      justify-items: start;
    }
    cc-toggle {
      --cc-toggle-color: #6999d3;
    }
    cc-toggle:not(.subtle) {
      --cc-toggle-img-filter: grayscale(100%) brightness(0.7);
      --cc-toggle-img-filter-selected: brightness(2);
    }
    cc-toggle.subtle {
      --cc-toggle-img-filter: grayscale(100%) brightness(0.7);
    }
  `,
```

File: src/styles/default-theme.js [hunk 5]
```diff
@@ -8,11 +8,143 @@ import { css } from 'lit-element';
...
-    --cc-chart-color-skeleton: #bbb;
-    --cc-chart-color-lightgray: #bbb;
-    --cc-chart-color-green: #30ab61;
-    --cc-chart-color-blue: #365bd3;
-    --cc-chart-color-orange: #ff9f40;
-    --cc-chart-color-red: #cf3942;
+    
+    /*region Color choices*/
+    /* color choices - these should not be referenced inside components (use decisions below instead)
+      tool used for grey shades: https://mdigi.tools/color-shades/#333333 (10 or 11 steps)
```
Comment (hsablonniere) [inline src/styles/default-theme.js:14]: Nice touch mentioning the tool.

File: src/styles/default-theme.js [hunk 6]
```diff
@@ -8,11 +8,143 @@ import { css } from 'lit-element';
...
+    -- Use this with --color-text-inverted --
+    For instance: submit buttons */
+    --color-bg-success: var(--color-green);
+    
+    /* Usage: elements containing short texts with a "caution" / "warning" meaning and usually interactive.
+    For instance: ? */
+    --color-bg-warning: var(--color-orange);
+    /*endregion*/
   }
 `;
```
Comment (hsablonniere) [inline src/styles/default-theme.js:150]: The whole file is nice:

* foldable sections :+1: 
* usage docs :+1: 
* naming of variables :+1:

**Review by hsablonniere — COMMENTED** [review]
This is impressive work!!
Congrats :clap:

File: src/atoms/cc-toggle.js (hunk 1 above)
Comment (hsablonniere) [reply src/atoms/cc-toggle.js:291]: It's OK :+1:

File: src/overview/cc-header-app.js (hunk 3 above)
Comment (hsablonniere) [reply src/overview/cc-header-app.js:388]: :+1:

File: src/atoms/cc-button.js [hunk 7]
```diff
@@ -297,7 +299,7 @@ export class CcButton extends LitElement {
 
         /* special case: we want to keep simple buttons subtle */
         .simple {
-          border-color: #aaa;
+          border-color: var(--color-grey-medium);
```
[the remark this answers is not in the document]
Comment (hsablonniere) [reply src/atoms/cc-button.js:302]: :+1:

**Comment by hsablonniere** [comment]
Feedbacks from looking at the preview:

* I like the "all form controls" story
  * We used to add titles in stories and display multiple components like this before
  * I think it proves we're reaching the limits of Storybook
* I'm a bit late on this but I think we should update the cc-toggle stories with custom colors so they can show off good examples:
  * color
  * toolbar
* I thought we decided some icons would be dual tone of two of our blues
  * the black in the backup icon could be our `--cc-color-blue-dark` or maybe like we do with encryption at rest
* WARNING: the skeleton of heptapod is broken ;-)

**Comment by hsablonniere** [comment]
> @hsablonniere should I import and use var(--color-bg-primary) inside the cc-toggle story (see below) ?

No, I would use hard coded colors in the story, like we do for the loader.

File: src/atoms/cc-select.js [hunk 8]
```diff
@@ -200,13 +201,15 @@ export class CcSelect extends LitElement {
         }
 
         select[disabled] {
-          background: #eee;
-          border-color: #eee;
+          background: var(--color-bg-neutral-disabled);
+          border-color: var(--color-bg-neutral-disabled);
+          color: var(--color-text-light);
+          opacity: 1;
```
Comment (florian-sanders-cc) [inline src/atoms/cc-select.js:207]: @hsablonniere changed this so that disabled inputs look the same.
You can check the preview to see the result, it is up to date.

Text is a little bit darker than what it was before since I removed opacity to make sure it remains contrasted enough. If you feel like it is too close to the readonly state, we can bring back opacity for now (since we have to deal with the disabled subject in general anyway).

File: src/atoms/cc-input-number.js [hunk 9]
```diff
@@ -276,7 +276,9 @@ export class CcInputNumber extends LitElement {
         }
 
         input[disabled] {
-          opacity: .75;
+          background-color: var(--color-bg-neutral-disabled);
+          color: var(--color-text-light);
+          opacity: 1;
```
Comment (florian-sanders-cc) [inline src/atoms/cc-input-number.js:281]: @hsablonniere changed this so that disabled inputs look the same.
You can check the preview to see the result, it is up to date.

Text is a little bit darker than what it was before since I removed opacity to make sure it remains contrasted enough. If you feel like it is too close to the readonly state, we can bring back opacity for now (since we have to deal with the disabled subject in general anyway).

File: src/atoms/cc-input-text.js [hunk 10]
```diff
@@ -389,7 +389,9 @@ export class CcInputText extends LitElement {
         }
 
         .input[disabled] {
-          opacity: .75;
+          background-color: var(--color-bg-neutral-disabled);
+          color: var(--color-text-light);
+          opacity: 1;
```
Comment (florian-sanders-cc) [inline src/atoms/cc-input-text.js:394]: @hsablonniere changed this so that disabled inputs look the same.
You can check the preview to see the result, it is up to date.

Text is a little bit darker than what it was before since I removed opacity to make sure it remains contrasted enough. If you feel like it is too close to the readonly state, we can bring back opacity for now (since we have to deal with the disabled subject in general anyway).

File: src/styles/default-theme.js [hunk 11]
```diff
@@ -8,11 +8,143 @@ import { css } from 'lit-element';
...
+    --color-grey-40: #a6a6a6;
+    --color-grey-30: #bfbfbf;
+    --color-grey-20: #d9d9d9;
+    --color-grey-15: #e7e7e7;
+    --color-grey-10: #f5f5f5;
+    --color-legacy-blue: #1ea2f1; /* do not use except inside cc-tile-instances*/
+    --color-legacy-green: #2faa60; /* do not use except inside cc-tile-instances*/
+    --color-legacy-red: #ff0032; /* do not use except inside cc-tile-instances*/
+    --color-orange: #c15807;
+    --color-purple-light: #3232ff26;
```
[the remark this answers is not in the document]
Comment (hsablonniere) [reply src/styles/default-theme.js:37]: Yep, I think so. Take the color you get hover a white background.
