### PR TITLE
fix(cc-block-details): improve focus outline and button transition

### LINKED ISSUE #1547: cc-block-details: missing focus outline style for the Command line button
## Context

The `Command line` button has no focus styling:

Black outline surrouding the Command line button

We need to add `:focus-visible` & use the `--cc-focus-outline` & `--cc-focus-outline-offset`.

### PR DESCRIPTION
**Pull request by Galimede**
Fixes #1547

## What does this PR do?                   
 
* Adds a focus-visible outline to the button,                                                                                                    
* Moves the transition from the button to its hover state as it was transitioning when in focus which we don't want.                                                                                                                                                                            
 
Question: transitioning the focus from square to rounded feels weird to me, should we round it too beforehand?

## How to review?

* Check the commit,
* Check the preview,
* One or two reviewers is enough.

### CODE REVIEW

**Review by clara-layus-cc — APPROVED** [review]
Well done !

As for the focus, I think it would indeed be a good idea to smooth things over from the outset to avoid any weird changes.

File: src/components/cc-block-details/cc-block-details.js [hunk 1]
```diff
@@ -77,27 +79,42 @@ export class CcBlockDetails extends LitElement {
...
           margin-bottom: 0;
         }
 
         .button:hover {
           border: solid 1px var(--cc-color-border-neutral-strong, #8c8c8c);
-          border-radius: var(--cc-border-radius-default, 0.25em);
+        }
+
+        .button:focus-visible {
+          border: none;
```
Comment (florian-sanders-cc) [inline src/components/cc-block-details/cc-block-details.js]: **fix/nitpick:** setting `border: none` here triggers a very small layout shift, do we really need this rule?

File: src/components/cc-block-details/cc-block-details.js [hunk 2]
```diff
@@ -77,27 +79,42 @@ export class CcBlockDetails extends LitElement {
...
-          transition: all 0.3s;
+          position: relative;
+          z-index: 1;
         }
 
         :host([is-open]) .button {
-          background-color: var(--cc-color-bg-default, #fff);
           border-radius: var(--cc-border-radius-default, 0.25em) var(--cc-border-radius-default, 0.25em) 0 0;
           margin-bottom: 0;
         }
```
Comment (florian-sanders-cc) [inline src/components/cc-block-details/cc-block-details.js]: **fix:** depending on what you've decided to do, you may remove this whole part


```suggestion
```

**Review by florian-sanders-cc — CHANGES_REQUESTED** [review]
