### PR TITLE
fix(cc-token-api-*): pass API bridge URL as a prop instead of hardcoding it

### LINKED ISSUE #1714: cc-token-api-*: API base URL should be passed as a prop
The API base URL in the curl example (`https://api-bridge.clever-cloud.com/v2/self`) is hardcoded in the component's template. It should be passed as a prop so the consumer can set the correct API URL depending on the environment.

Affected components:
- `cc-token-api-update-form`
- `cc-token-api-list`
- `cc-token-api-creation-form`

### PR DESCRIPTION
**Pull request by Galimede**
Fixes #1714

## What does this PR do?

- Adds an `apiBridgeHref` prop to `cc-token-api-update-form`, `cc-token-api-list`, and `cc-token-api-creation-form`,
- Replaces the hardcoded `https://api-bridge.clever-cloud.com` in the curl example with the prop value,
- Uses `new URL()` to safely join the path (handles trailing slashes),
- Smart components pass `apiConfig.AUTH_BRIDGE_HOST` to the new prop,
- Defaults to `https://api-bridge.clever-cloud.com` when the prop is not set.

## How to review?

- Check the code,
- Check the `withCustomApiBridgeHref` story in Storybook for each component,
- Two reviewers should be enough.

### CODE REVIEW

**Review by pdesoyres-cc — APPROVED** [review]
LGTM

**Review by HeleneAmouzou — APPROVED** [review]
LGTM ! 👏

File: src/components/cc-token-api-creation-form/cc-token-api-creation-form.js [hunk 1]
```diff
@@ -394,7 +398,7 @@ export class CcTokenApiCreationForm extends LitElement {
               <dt>${i18n('cc-token-api-creation-form.cli.content.use-token')}</dt>
               <dd>
                 <cc-code>
-                  curl -H "Authorization: Bearer &lt;TOKEN&gt;" https://api-bridge.clever-cloud.com/v2/self
+                  curl -H "Authorization: Bearer &lt;TOKEN&gt;" ${new URL('/v2/self', this.apiBridgeHref)}
```
Comment (roberttran-cc) [inline src/components/cc-token-api-creation-form/cc-token-api-creation-form.js]: **🫣 nitpick:** 


```suggestion
                  curl -H "Authorization: Bearer &lt;TOKEN&gt;" ${new URL('/v2/self', this.apiBridgeHref).href}
```

File: src/components/cc-token-api-list/cc-token-api-list.js [hunk 2]
```diff
@@ -207,7 +211,7 @@ export class CcTokenApiList extends LitElement {
               <dt>${i18n('cc-token-api-list.cli.content.use-token')}</dt>
               <dd>
                 <cc-code>
-                  curl -H "Authorization: Bearer &lt;TOKEN&gt;" https://api-bridge.clever-cloud.com/v2/self
+                  curl -H "Authorization: Bearer &lt;TOKEN&gt;" ${new URL('/v2/self', this.apiBridgeHref)}
```
Comment (roberttran-cc) [inline src/components/cc-token-api-list/cc-token-api-list.js]: **🫣 nitpick:** 


```suggestion
                  curl -H "Authorization: Bearer &lt;TOKEN&gt;" ${new URL('/v2/self', this.apiBridgeHref).href}
```

File: src/components/cc-token-api-update-form/cc-token-api-update-form.js [hunk 3]
```diff
@@ -102,7 +106,7 @@ export class CcTokenApiUpdateForm extends LitElement {
               <dt>${i18n('cc-token-api-update-form.cli.content.use-token')}</dt>
               <dd>
                 <cc-code>
-                  curl -H "Authorization: Bearer &lt;TOKEN&gt;" https://api-bridge.clever-cloud.com/v2/self
+                  curl -H "Authorization: Bearer &lt;TOKEN&gt;" ${new URL('/v2/self', this.apiBridgeHref)}
```
Comment (roberttran-cc) [inline src/components/cc-token-api-update-form/cc-token-api-update-form.js]: **🫣 nitpick:** 

```suggestion
                  curl -H "Authorization: Bearer &lt;TOKEN&gt;" ${new URL('/v2/self', this.apiBridgeHref).href}
```

**Review by roberttran-cc — APPROVED** [review]
LGTM, nitpicks only!

Also, smart demos for these components are broken, but same on `main`. Nice to fix here if easy, otherwise fine to skip.

**Review by florian-sanders-cc — APPROVED** [review]
Gg @Galimede and thanks for handling this, a small nitpick about the prop name: I prefer `apiBridgeBaseUrl` to make it clear that it needs to be completed with a path but it's a detail really 😉
